// Code generated by mockery v2.44.1. DO NOT EDIT.

package mocks

import (
	domain "TaskManager/task-manager/Domain"

	mock "github.com/stretchr/testify/mock"
)

// TaskUsecase is an autogenerated mock type for the TaskUsecase type
type TaskUsecase struct {
	mock.Mock
}

// AddTask provides a mock function with given fields: role, user_id, task
func (_m *TaskUsecase) AddTask(role string, user_id string, task domain.Task) (string, error) {
	ret := _m.Called(role, user_id, task)

	if len(ret) == 0 {
		panic("no return value specified for AddTask")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, domain.Task) (string, error)); ok {
		return rf(role, user_id, task)
	}
	if rf, ok := ret.Get(0).(func(string, string, domain.Task) string); ok {
		r0 = rf(role, user_id, task)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string, domain.Task) error); ok {
		r1 = rf(role, user_id, task)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteTaskByID provides a mock function with given fields: role, user_id, task_id
func (_m *TaskUsecase) DeleteTaskByID(role string, user_id string, task_id string) error {
	ret := _m.Called(role, user_id, task_id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTaskByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(role, user_id, task_id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllTasks provides a mock function with given fields: role, user_id
func (_m *TaskUsecase) GetAllTasks(role string, user_id string) ([]domain.Task, error) {
	ret := _m.Called(role, user_id)

	if len(ret) == 0 {
		panic("no return value specified for GetAllTasks")
	}

	var r0 []domain.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) ([]domain.Task, error)); ok {
		return rf(role, user_id)
	}
	if rf, ok := ret.Get(0).(func(string, string) []domain.Task); ok {
		r0 = rf(role, user_id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(role, user_id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTaskByID provides a mock function with given fields: role, user_id, task_id
func (_m *TaskUsecase) GetTaskByID(role string, user_id string, task_id string) (domain.Task, error) {
	ret := _m.Called(role, user_id, task_id)

	if len(ret) == 0 {
		panic("no return value specified for GetTaskByID")
	}

	var r0 domain.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string) (domain.Task, error)); ok {
		return rf(role, user_id, task_id)
	}
	if rf, ok := ret.Get(0).(func(string, string, string) domain.Task); ok {
		r0 = rf(role, user_id, task_id)
	} else {
		r0 = ret.Get(0).(domain.Task)
	}

	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(role, user_id, task_id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateTaskByID provides a mock function with given fields: role, user_id, task, id
func (_m *TaskUsecase) UpdateTaskByID(role string, user_id string, task domain.Task, id string) error {
	ret := _m.Called(role, user_id, task, id)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTaskByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, domain.Task, string) error); ok {
		r0 = rf(role, user_id, task, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTaskUsecase creates a new instance of TaskUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTaskUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *TaskUsecase {
	mock := &TaskUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
